### ISSUE TITLE
[Colored Container Tab] Border color for unselected tab

### ISSUE THREAD

**Issue by V4ldum** [ocean-mars/things#1]
Hey, 

On my side the border only appears when a tab is selected (see screenshots). I was wondering if this was the correct behaviour or an issue with my setup ? I already tried disabling all other mods but nothing changed.

The GitHub tab is selected and correctly has the border :
![image](https://github.com/user-attachments/assets/2a3f76e5-cea6-47a6-905b-b1d276b7bbb8)

The GitHub tab is not selected and no longer has the border :
![image](https://github.com/user-attachments/assets/2297668f-aeae-4654-93f8-edf81c078e10)

**Comment by ocean-mars** [comment]
Use the code below in userChrome

#tabbrowser-tabs {
  & .tabbrowser-tab {
    .tab-background {
      border: 2px solid var(--identity-icon-color) !important;
      opacity: 0.8 !important;
    }
  }
}

**Comment by ocean-mars** [comment]
Use the code below in userChrome.css

#tabbrowser-tabs {
& .tabbrowser-tab {
.tab-background {
border: 2px solid var(--identity-icon-color) !important;
opacity: 0.8 !important;
}
}
}

**Comment by ocean-mars** [comment]
& remove the mod from zen mod store. Or, you can also edit the mod file, go to profile folder>chrome>zen-themes> edit "3ff55ba7-4690-4f74-96a8-9e4416685e4e", Delete existing code & paste this,

#tabbrowser-tabs {
& .tabbrowser-tab {
.tab-background {
border: 2px solid var(--identity-icon-color) !important;
opacity: 0.8 !important;
}
}
}

**Comment by ocean-mars** [comment]
Or remove the mod & put the code in userChrome.css

#tabbrowser-tabs {
& .tabbrowser-tab {
.tab-background {
border: 2px solid var(--identity-icon-color) !important;
opacity: 0.8 !important;
}
}
}

**Comment by V4ldum** [comment]
Thanks you very much, I managed to make it work !

For documentation purpose, the following code was also necessary to hide the line from Zen itself :
```css
.tab-context-line{
	display: none !important;
}
```

An improvement could be adding the same behaviour for pinned tabs but I'm not sure how much you want to maintain the mod. It's not a big issue and it doesn't bother me as is.

**Comment by Ni-zav** [comment]
thanks, this is what i need. I thought i was going to make PR but this issue will do.

and yea i prefer it is colored even on inactive tabs.

**Comment by ocean-mars** [comment]
@Ni-zav I'm using this code now,

/* Selected-Tabs Theme */
.tabbrowser-tab:is([selected],
[visuallyselected],
[multiselected])
  .tab-background {
  background-color: color-mix(
    in srgb,
    var(--identity-tab-color, var(--tab-group-color-gray-invert)) 15%,
    transparent
  ) !important;
  border: 2.5px solid
    color-mix(
      in srgb,
      var(--identity-tab-color, var(--tab-group-color-gray-invert)) 20%,
      transparent
    ) !important;
  opacity: 0.8 !important;
  border-left: 32px solid
    color-mix(
      in srgb,
      var(--identity-tab-color, var(--tab-group-color-gray-invert)) 20%,
      transparent
    ) !important;
}

**Comment by ocean-mars** [comment]
@Ni-zav if you want to have inactive tabs colored as well, use this code:

/* Selected-Tabs Theme */
  .tab-background {
  background-color: color-mix(
    in srgb,
    var(--identity-tab-color, var(--tab-group-color-gray-invert)) 15%,
    transparent
  ) !important;
  border: 2.5px solid
    color-mix(
      in srgb,
      var(--identity-tab-color, var(--tab-group-color-gray-invert)) 20%,
      transparent
    ) !important;
  opacity: 0.8 !important;
  border-left: 32px solid
    color-mix(
      in srgb,
      var(--identity-tab-color, var(--tab-group-color-gray-invert)) 20%,
      transparent
    ) !important;
}
